data_cfg:
  dataset_name: CCPG
  dataset_root: G:/Gait/DataSets/CCPG/Sil_Pose
  dataset_partition: ./datasets/CCPG/CCPG.json
  num_workers: 2
  data_in_use:
    - true   # 0_pose.pkl
    - true   # 1_sil.pkl
  remove_no_gallery: false
  test_dataset_name: CCPG

evaluator_cfg:
  enable_float16: true
  restore_ckpt_strict: true
  restore_hint: 90000
  save_name: CAR-Gait_CCPG_4070Ti_16G
  eval_func: evaluate_CCPG
  metric: euc
  sampler:
    batch_shuffle: false
    batch_size: 1
    sample_type: all_ordered
    frames_all_limit: 360
  transform:
    - type: NormalizeEmpty
    - type: BaseSilCuttingTransform

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 1.0
    scale: 16
    type: CrossEntropyLoss
    log_prefix: softmax
    log_accuracy: true

model_cfg:
  model: CAR_Gait
  use_emb2: false
  joint_format: coco
  parts_num: 16
  embedding_channels: 192
  aux_warmup_iter: 20000
  condition_keys:
    - U0_D0
    - U0_D0_BG
    - U1_D0
    - U1_D1
    - U2_D2
    - U3_D3
    - U0_D3
  Backbone:
    layers:
      - 1
      - 1
      - 1
      - 1
    channels:
      - 48
      - 96
      - 192
      - 384
  PoseEncoder:
    hidden_channels:
      - 48
      - 96
      - 96
  SeparateBNNecks:
    class_num: 100
  loss_weights:
    condition_adv: 0.2
    state_consistency: 0.2
    pose_sil: 0.05

optimizer_cfg:
  lr: 0.08
  momentum: 0.9
  solver: SGD
  weight_decay: 0.0005

scheduler_cfg:
  gamma: 0.1
  milestones:
    - 70000
    - 110000
    - 140000
  scheduler: MultiStepLR

trainer_cfg:
  enable_float16: true
  fix_BN: false
  with_test: false
  log_iter: 100
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 10000
  save_name: CAR-Gait_CCPG_4070Ti_16G
  sync_BN: false
  total_iter: 160000
  sampler:
    batch_shuffle: true
    batch_size:
      - 4
      - 8
    frames_num_fixed: 30
    frames_skip_num: 4
    sample_type: fixed_ordered
    type: TripletSampler
  transform:
    - type: Compose
      trf_cfg:
        - type: NormalizeEmpty
        - type: FlipSequence
          probability: 0.5
        - type: JointNoise
          std: 0.1
    - type: Compose
      trf_cfg:
        - type: RandomPerspective
          prob: 0.2
        - type: BaseSilCuttingTransform
        - type: RandomHorizontalFlip
          prob: 0.2
        - type: RandomRotate
          prob: 0.2
